/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  CurveV1FactoryPool,
  CurveV1FactoryPoolInterface,
} from "../../Curve/CurveV1FactoryPool";

const _abi = [
  {
    stateMutability: "view",
    type: "function",
    name: "get_dy",
    inputs: [
      {
        name: "i",
        type: "int128",
      },
      {
        name: "j",
        type: "int128",
      },
      {
        name: "dx",
        type: "uint256",
      },
    ],
    outputs: [
      {
        name: "",
        type: "uint256",
      },
    ],
  },
];

export class CurveV1FactoryPool__factory {
  static readonly abi = _abi;
  static createInterface(): CurveV1FactoryPoolInterface {
    return new utils.Interface(_abi) as CurveV1FactoryPoolInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CurveV1FactoryPool {
    return new Contract(address, _abi, signerOrProvider) as CurveV1FactoryPool;
  }
}
