/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { VeCRV__factory } from "./VeCRV__factory";
export { VotingCurve__factory } from "./VotingCurve__factory";
