/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AragonAgent } from "./AragonAgent";
export type { AragonVoting } from "./AragonVoting";
export type { GaugeController } from "./GaugeController";
export type { GaugeFactory } from "./GaugeFactory";
