export const abi = [
  {
    inputs: [
      { internalType: "uint256", name: "index", type: "uint256" },
      { internalType: "address", name: "account", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
      {
        internalType: "bytes32[]",
        name: "merkleProof",
        type: "bytes32[]",
      },
      { internalType: "uint256", name: "minAmountOut", type: "uint256" },
      { internalType: "address", name: "to", type: "address" },
      { internalType: "bool", name: "lock", type: "bool" },
    ],
    name: "claimFromDistributorAsCvx",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "index", type: "uint256" },
      { internalType: "address", name: "account", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
      {
        internalType: "bytes32[]",
        name: "merkleProof",
        type: "bytes32[]",
      },
      { internalType: "uint256", name: "minAmountOut", type: "uint256" },
      { internalType: "address", name: "to", type: "address" },
    ],
    name: "claimFromDistributorAsEth",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "index", type: "uint256" },
      { internalType: "address", name: "account", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
      {
        internalType: "bytes32[]",
        name: "merkleProof",
        type: "bytes32[]",
      },
      { internalType: "uint256", name: "minAmountOut", type: "uint256" },
      { internalType: "address", name: "to", type: "address" },
    ],
    name: "claimFromDistributorAsFxs",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "index", type: "uint256" },
      { internalType: "address", name: "account", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
      {
        internalType: "bytes32[]",
        name: "merkleProof",
        type: "bytes32[]",
      },
      { internalType: "uint256", name: "minAmountOut", type: "uint256" },
      { internalType: "address", name: "to", type: "address" },
    ],
    name: "claimFromDistributorAsUnderlying",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "index", type: "uint256" },
      { internalType: "address", name: "account", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
      {
        internalType: "bytes32[]",
        name: "merkleProof",
        type: "bytes32[]",
      },
      { internalType: "uint256", name: "minAmountOut", type: "uint256" },
      { internalType: "address", name: "to", type: "address" },
    ],
    name: "claimFromDistributorAsUsdt",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "index", type: "uint256" },
      { internalType: "address", name: "account", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
      {
        internalType: "bytes32[]",
        name: "merkleProof",
        type: "bytes32[]",
      },
      { internalType: "uint256", name: "minAmountOut", type: "uint256" },
      { internalType: "address", name: "router", type: "address" },
      { internalType: "address", name: "outputToken", type: "address" },
      { internalType: "address", name: "to", type: "address" },
    ],
    name: "claimFromDistributorViaUniV2EthPair",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;
