/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as registries from "./Registries";
export type { registries };
import type * as standards from "./Standards";
export type { standards };
import type * as union from "./Union";
export type { union };
export * as factories from "./factories";
export type { AssetRegistry } from "./Registries/AssetRegistry";
export { AssetRegistry__factory } from "./factories/Registries/AssetRegistry__factory";
export type { ERC20 } from "./Standards/ERC20";
export { ERC20__factory } from "./factories/Standards/ERC20__factory";
export type { MerkleDistributor2 } from "./Union/MerkleDistributor2";
export { MerkleDistributor2__factory } from "./factories/Union/MerkleDistributor2__factory";
