export const abi = [
  {
    constant: false,
    inputs: [
      { name: "_voteId", type: "uint256" },
      { name: "_yeaPct", type: "uint256" },
      { name: "_nayPct", type: "uint256" },
      { name: "_executesIfDecided", type: "bool" },
    ],
    name: "votePct",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      { name: "_voteId", type: "uint256" },
      { name: "_voter", type: "address" },
    ],
    name: "getVoterState",
    outputs: [{ name: "", type: "uint8" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [{ name: "_voteId", type: "uint256" }],
    name: "getVote",
    outputs: [
      { name: "open", type: "bool" },
      { name: "executed", type: "bool" },
      { name: "startDate", type: "uint64" },
      { name: "snapshotBlock", type: "uint64" },
      { name: "supportRequired", type: "uint64" },
      { name: "minAcceptQuorum", type: "uint64" },
      { name: "yea", type: "uint256" },
      { name: "nay", type: "uint256" },
      { name: "votingPower", type: "uint256" },
      { name: "script", type: "bytes" },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [{ name: "_voteId", type: "uint256" }],
    name: "canExecute",
    outputs: [{ name: "", type: "bool" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      { name: "_voteId", type: "uint256" },
      { name: "_voter", type: "address" },
    ],
    name: "canVote",
    outputs: [{ name: "", type: "bool" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "token",
    outputs: [{ name: "", type: "address" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "PCT_BASE",
    outputs: [{ name: "", type: "uint64" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [{ name: "_voteId", type: "uint256" }],
    name: "executeVote",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;
