/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export interface ZapsUCrvV2Interface extends utils.Interface {
  functions: {
    "claimFromVaultAndStakeIn3PoolConvex(uint256,uint256,address)": FunctionFragment;
    "claimFromVaultAsCrv(uint256,uint256,address)": FunctionFragment;
    "claimFromVaultAsCvx(uint256,uint256,address,bool)": FunctionFragment;
    "claimFromVaultAsEth(uint256,uint256,address)": FunctionFragment;
    "claimFromVaultAsUsdt(uint256,uint256,address)": FunctionFragment;
    "claimFromVaultViaUniV2EthPair(uint256,uint256,address,address,address)": FunctionFragment;
    "depositFromCrv(uint256,uint256,address)": FunctionFragment;
    "depositFromEth(uint256,address)": FunctionFragment;
    "depositFromUCrv(uint256,uint256,address)": FunctionFragment;
    "depositViaUniV2EthPair(uint256,uint256,address,address,address)": FunctionFragment;
    "setApprovals()": FunctionFragment;
    "vault()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "claimFromVaultAndStakeIn3PoolConvex"
      | "claimFromVaultAsCrv"
      | "claimFromVaultAsCvx"
      | "claimFromVaultAsEth"
      | "claimFromVaultAsUsdt"
      | "claimFromVaultViaUniV2EthPair"
      | "depositFromCrv"
      | "depositFromEth"
      | "depositFromUCrv"
      | "depositViaUniV2EthPair"
      | "setApprovals"
      | "vault"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "claimFromVaultAndStakeIn3PoolConvex",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "claimFromVaultAsCrv",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "claimFromVaultAsCvx",
    values: [BigNumberish, BigNumberish, string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "claimFromVaultAsEth",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "claimFromVaultAsUsdt",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "claimFromVaultViaUniV2EthPair",
    values: [BigNumberish, BigNumberish, string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "depositFromCrv",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "depositFromEth",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "depositFromUCrv",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "depositViaUniV2EthPair",
    values: [BigNumberish, BigNumberish, string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setApprovals",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "vault", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "claimFromVaultAndStakeIn3PoolConvex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimFromVaultAsCrv",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimFromVaultAsCvx",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimFromVaultAsEth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimFromVaultAsUsdt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimFromVaultViaUniV2EthPair",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositFromCrv",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositFromEth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositFromUCrv",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositViaUniV2EthPair",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setApprovals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vault", data: BytesLike): Result;

  events: {};
}

export interface ZapsUCrvV2 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ZapsUCrvV2Interface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    claimFromVaultAndStakeIn3PoolConvex(
      amount: BigNumberish,
      minAmountOut: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    claimFromVaultAsCrv(
      amount: BigNumberish,
      minAmountOut: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    claimFromVaultAsCvx(
      amount: BigNumberish,
      minAmountOut: BigNumberish,
      to: string,
      lock: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    claimFromVaultAsEth(
      amount: BigNumberish,
      minAmountOut: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    claimFromVaultAsUsdt(
      amount: BigNumberish,
      minAmountOut: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    claimFromVaultViaUniV2EthPair(
      amount: BigNumberish,
      minAmountOut: BigNumberish,
      router: string,
      outputToken: string,
      to: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    depositFromCrv(
      amount: BigNumberish,
      minAmountOut: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    depositFromEth(
      minAmountOut: BigNumberish,
      to: string,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    depositFromUCrv(
      amount: BigNumberish,
      minAmountOut: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    depositViaUniV2EthPair(
      amount: BigNumberish,
      minAmountOut: BigNumberish,
      router: string,
      inputToken: string,
      to: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setApprovals(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    vault(overrides?: CallOverrides): Promise<[string]>;
  };

  claimFromVaultAndStakeIn3PoolConvex(
    amount: BigNumberish,
    minAmountOut: BigNumberish,
    to: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  claimFromVaultAsCrv(
    amount: BigNumberish,
    minAmountOut: BigNumberish,
    to: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  claimFromVaultAsCvx(
    amount: BigNumberish,
    minAmountOut: BigNumberish,
    to: string,
    lock: boolean,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  claimFromVaultAsEth(
    amount: BigNumberish,
    minAmountOut: BigNumberish,
    to: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  claimFromVaultAsUsdt(
    amount: BigNumberish,
    minAmountOut: BigNumberish,
    to: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  claimFromVaultViaUniV2EthPair(
    amount: BigNumberish,
    minAmountOut: BigNumberish,
    router: string,
    outputToken: string,
    to: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  depositFromCrv(
    amount: BigNumberish,
    minAmountOut: BigNumberish,
    to: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  depositFromEth(
    minAmountOut: BigNumberish,
    to: string,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  depositFromUCrv(
    amount: BigNumberish,
    minAmountOut: BigNumberish,
    to: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  depositViaUniV2EthPair(
    amount: BigNumberish,
    minAmountOut: BigNumberish,
    router: string,
    inputToken: string,
    to: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setApprovals(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  vault(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    claimFromVaultAndStakeIn3PoolConvex(
      amount: BigNumberish,
      minAmountOut: BigNumberish,
      to: string,
      overrides?: CallOverrides
    ): Promise<void>;

    claimFromVaultAsCrv(
      amount: BigNumberish,
      minAmountOut: BigNumberish,
      to: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    claimFromVaultAsCvx(
      amount: BigNumberish,
      minAmountOut: BigNumberish,
      to: string,
      lock: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    claimFromVaultAsEth(
      amount: BigNumberish,
      minAmountOut: BigNumberish,
      to: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    claimFromVaultAsUsdt(
      amount: BigNumberish,
      minAmountOut: BigNumberish,
      to: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    claimFromVaultViaUniV2EthPair(
      amount: BigNumberish,
      minAmountOut: BigNumberish,
      router: string,
      outputToken: string,
      to: string,
      overrides?: CallOverrides
    ): Promise<void>;

    depositFromCrv(
      amount: BigNumberish,
      minAmountOut: BigNumberish,
      to: string,
      overrides?: CallOverrides
    ): Promise<void>;

    depositFromEth(
      minAmountOut: BigNumberish,
      to: string,
      overrides?: CallOverrides
    ): Promise<void>;

    depositFromUCrv(
      amount: BigNumberish,
      minAmountOut: BigNumberish,
      to: string,
      overrides?: CallOverrides
    ): Promise<void>;

    depositViaUniV2EthPair(
      amount: BigNumberish,
      minAmountOut: BigNumberish,
      router: string,
      inputToken: string,
      to: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setApprovals(overrides?: CallOverrides): Promise<void>;

    vault(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    claimFromVaultAndStakeIn3PoolConvex(
      amount: BigNumberish,
      minAmountOut: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    claimFromVaultAsCrv(
      amount: BigNumberish,
      minAmountOut: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    claimFromVaultAsCvx(
      amount: BigNumberish,
      minAmountOut: BigNumberish,
      to: string,
      lock: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    claimFromVaultAsEth(
      amount: BigNumberish,
      minAmountOut: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    claimFromVaultAsUsdt(
      amount: BigNumberish,
      minAmountOut: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    claimFromVaultViaUniV2EthPair(
      amount: BigNumberish,
      minAmountOut: BigNumberish,
      router: string,
      outputToken: string,
      to: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    depositFromCrv(
      amount: BigNumberish,
      minAmountOut: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    depositFromEth(
      minAmountOut: BigNumberish,
      to: string,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    depositFromUCrv(
      amount: BigNumberish,
      minAmountOut: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    depositViaUniV2EthPair(
      amount: BigNumberish,
      minAmountOut: BigNumberish,
      router: string,
      inputToken: string,
      to: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setApprovals(overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    vault(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    claimFromVaultAndStakeIn3PoolConvex(
      amount: BigNumberish,
      minAmountOut: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    claimFromVaultAsCrv(
      amount: BigNumberish,
      minAmountOut: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    claimFromVaultAsCvx(
      amount: BigNumberish,
      minAmountOut: BigNumberish,
      to: string,
      lock: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    claimFromVaultAsEth(
      amount: BigNumberish,
      minAmountOut: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    claimFromVaultAsUsdt(
      amount: BigNumberish,
      minAmountOut: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    claimFromVaultViaUniV2EthPair(
      amount: BigNumberish,
      minAmountOut: BigNumberish,
      router: string,
      outputToken: string,
      to: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    depositFromCrv(
      amount: BigNumberish,
      minAmountOut: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    depositFromEth(
      minAmountOut: BigNumberish,
      to: string,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    depositFromUCrv(
      amount: BigNumberish,
      minAmountOut: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    depositViaUniV2EthPair(
      amount: BigNumberish,
      minAmountOut: BigNumberish,
      router: string,
      inputToken: string,
      to: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setApprovals(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    vault(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
