/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export interface AssetRegistryInterface extends utils.Interface {
  functions: {
    "assetAllocations(address,uint256)": FunctionFragment;
    "getAllocations(address[])": FunctionFragment;
    "recordAllocation(uint16[16])": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "assetAllocations"
      | "getAllocations"
      | "recordAllocation"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "assetAllocations",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllocations",
    values: [string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "recordAllocation",
    values: [BigNumberish[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "assetAllocations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllocations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordAllocation",
    data: BytesLike
  ): Result;

  events: {};
}

export interface AssetRegistry extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: AssetRegistryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    assetAllocations(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[number]>;

    getAllocations(
      members: string[],
      overrides?: CallOverrides
    ): Promise<[number[][]]>;

    recordAllocation(
      choices: BigNumberish[],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  assetAllocations(
    arg0: string,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<number>;

  getAllocations(
    members: string[],
    overrides?: CallOverrides
  ): Promise<number[][]>;

  recordAllocation(
    choices: BigNumberish[],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    assetAllocations(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<number>;

    getAllocations(
      members: string[],
      overrides?: CallOverrides
    ): Promise<number[][]>;

    recordAllocation(
      choices: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    assetAllocations(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAllocations(
      members: string[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    recordAllocation(
      choices: BigNumberish[],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    assetAllocations(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAllocations(
      members: string[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    recordAllocation(
      choices: BigNumberish[],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
