/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AssetRegistry } from "./AssetRegistry";
export type { VotiumRegistry } from "./VotiumRegistry";
