name: Bun CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Checkout submodule
        run: |
          git submodule init src/Apps/CurveMonitor/phil
          git submodule update src/Apps/CurveMonitor/phil
      - name: Use Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: git config --global url."https://".insteadOf ssh://
      - run: bun pm cache rm
      - run: bun install
      - run: bun --cwd src/Apps/LlamaAirforce build
      - run: bun --cwd src/Apps/CurveMonitor build
      - run: bun --cwd src/Apps/PrismaMonitor build
      - run: bun run typecheck
      - run: bun run lint:framework
      - run: bun --cwd src/Apps/LlamaAirforce lint
      - run: bun --cwd src/Apps/CurveMonitor lint
      - run: bun --cwd src/Apps/PrismaMonitor lint
      - run: bun test
