name: Bun CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Checkout submodule
        run: |
          git submodule init src/Apps/CurveMonitor/phil
          git submodule update src/Apps/CurveMonitor/phil
      - name: Use Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: git config --global url."https://".insteadOf ssh://
      - run: bun install
      - run: bun run typecheck
      - run: bun run lint:laf
      - run: bun run lint:cm
      - run: bun run lint:pm
      - run: bun run build:laf
      - run: bun run build:cm
      - run: bun run build:pm
      - run: bun test
